/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

/** 
 * MyEclipse Struts
 * Creation date: 05-08-2017
 * 
 * XDoclet definition:
 * @struts.form name="userVoForm"
 */
public class UserVoForm extends ActionForm {
	private int stuno; 
	private String name;
	private String password;
	private int age;
	private String sex;
	private String cadeid;
	private String classname;
	public int getStuno() {
		return stuno;
	}
	public void setStuno(int stuno) {
		this.stuno = stuno;
	}
	public String getCadeid() {
		return cadeid;
	}
	public void setCadeid(String cadeid) {
		this.cadeid = cadeid;
	}
	public String getClassname() {
		return classname;
	}
	public void setClassname(String classname) {
		this.classname = classname;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public int getAge() {
		return age;
	}
	public void setAge(int age) {
		this.age = age;
	}
	public String getSex() {
		return sex;
	}
	public void setSex(String sex) {
		this.sex = sex;
	}
	@Override
	public String toString() {
		return "姓名="+this.name+"年龄="+this.age+"性别="+this.sex;
	}
	
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		System.out.println(request.getParameter("action"));
		ActionErrors error = new ActionErrors();
		if(name.equals("")||name==null){
			error.add("stuno",new ActionMessage("error.name.required"));
			return error;
		}else if(password.equals("")||password==null){
			error.add("password",new ActionMessage("error.password.required"));
			return error;
		}else if(age<1 || age>150){
			error.add("age",new ActionMessage("error.age.required"));
			return error;
		}else if(cadeid.equals("")||cadeid==null){
			error.add("cadeid",new ActionMessage("error.cadeid.required"));
			return error;
		}else if(classname.equals("")||classname==null){
			error.add("classname",new ActionMessage("error.classname.required"));
			return error;
		}
		return error;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
}