/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;

import javax.jms.Session;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

import com.impl.Pageuser;
import com.impl.Strutsimpl;
import com.yourcompany.struts.form.UserVoForm;

 		
public class UseractionAction extends Action {
	Strutsimpl impl = new Strutsimpl();
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		UserVoForm uservoform = (UserVoForm)form;
		ActionErrors errors = new ActionErrors();
		String action = request.getParameter("action");
		HttpSession session =request.getSession();
		if(!action.equals("")){
				if(action.equals("login")){
					String name=uservoform.getName().trim();
					String pass=uservoform.getPassword().trim();
				boolean isok=impl.selectuser(name, pass);
				if(isok){
					return mapping.findForward("succ");
				}else{
					errors.add("stuno", new ActionMessage("error.stuno.required"));
					saveErrors(request, errors);
					return mapping.findForward("error");
				}
			}else if(action.equals("add")){
				int userid = uservoform.getStuno();
				String name=uservoform.getName().trim();
				String pass=uservoform.getPassword().trim();
				int age = uservoform.getAge();
				String sex = uservoform.getSex();
				String cadeid = uservoform.getCadeid().trim();
				String classname = uservoform.getClassname().trim();
				UserVoForm uservo = new UserVoForm();
				uservo.setStuno(userid);
				uservo.setName(name);
				uservo.setPassword(pass);
				uservo.setAge(age);
				uservo.setSex(sex);
				uservo.setCadeid(cadeid);
				uservo.setClassname(classname);
				impl.addstudent(uservo);
				
				session.setAttribute("msg", uservo);
				return mapping.findForward("reg");
			}else if(action.equals("lists")){
				
			}
		}
		return null;
	}
	public void pagelist(HttpServletRequest request,HttpServletResponse response)
	throws ServletException,IOException{
		Pageuser page = new Pageuser();
		page.setPagebersum(impl.countuser("users"));
		String currentpage = request.getParameter("currentpage");
		String handle = request.getParameter("handle");
		if(currentpage.equals("") || currentpage==null){
			page.setCurrentpage(1);
		}else{
			page.setCurrentpage(Integer.parseInt(currentpage));
		}
		if(handle.equals("") || handle==null){
			page.setHandle("firstpage");
		}else{
			page.setHandle(handle);
		}
		List<UserVoForm> list = impl.pageuser(page.getPagebersize(), page.getStarlocal());
		request.setAttribute("list",list);
		request.setAttribute("page",page);
	}
}